In [ ]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "college_students_habits_1M.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "sharmajicoder/college-students-habits-and-performance",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipython-input-932/1738183528.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
First 5 records:    study_hours  attendance  assignment_completion  midterm_score  final_score  \
0     3.014684    67.00599              51.595387      57.211285    61.653540
1     3.665277    73.28455              69.749020      57.552320    62.062782
2     2.703784    72.32519              92.837640      44.568970    46.482760
3     3.445073    74.75687              85.189026      52.040790    55.448948
4     0.192687    55.05021              64.520620      32.815000    32.378000

   project_score  backlogs  sleep_hours    stress    anxiety  ...  \
0      65.397200         4     5.993893  4.287966  58.146000  ...
1      65.715500         3     6.949383  1.841224  41.945290  ...
2      53.597702         2     6.703293  3.863112  56.555750  ...
3      60.571404         2     6.498832  5.073206  65.171420  ...
4      42.627330         5     6.552570  1.000000  30.725826  ...

   hostel_student  extracurricular_hours  phone_unlocks_per_day  previous_gpa  \
0               0               1.958940              73.727480      5.721128
1               0               3.146447              48.468456      5.755232
2               1               5.551245              46.623684      4.456897
3               1               4.543216              47.909600      5.204079
4               1               4.447042              73.316520      3.281500

   class_participation  weekly_study_sessions  group_study_hours  \
0             3.587111               2.814086           1.814086
1             4.820090               2.836821           1.836821
2             5.493774               1.971265           0.971265
3             5.481987               2.469386           1.469386
4             2.822375               1.187667           0.187667

   financial_stress       gpa  performance_level
0          5.491878  0.546729                Low
1          2.876881  0.707133                Low
2          5.704047  0.868230                Low
3          6.596658  0.729216                Low
4          4.602954  0.370964                Low

[5 rows x 42 columns]

In [ ]:
df.head()

,study_hours,attendance,assignment_completion,midterm_score,final_score,project_score,backlogs,sleep_hours,stress,anxiety,...,hostel_student,extracurricular_hours,phone_unlocks_per_day,previous_gpa,class_participation,weekly_study_sessions,group_study_hours,financial_stress,gpa,performance_level
0,3.014684,67.00599,51.595387,57.211285,61.653540,65.397200,4,5.993893,4.287966,58.146000,...,0,1.958940,73.727480,5.721128,3.587111,2.814086,1.814086,5.491878,0.546729,Low
1,3.665277,73.28455,69.749020,57.552320,62.062782,65.715500,3,6.949383,1.841224,41.945290,...,0,3.146447,48.468456,5.755232,4.820090,2.836821,1.836821,2.876881,0.707133,Low
2,2.703784,72.32519,92.837640,44.568970,46.482760,53.597702,2,6.703293,3.863112,56.555750,...,1,5.551245,46.623684,4.456897,5.493774,1.971265,0.971265,5.704047,0.868230,Low
3,3.445073,74.75687,85.189026,52.040790,55.448948,60.571404,2,6.498832,5.073206,65.171420,...,1,4.543216,47.909600,5.204079,5.481987,2.469386,1.469386,6.596658,0.729216,Low
4,0.192687,55.05021,64.520620,32.815000,32.378000,42.627330,5,6.552570,1.000000,30.725826,...,1,4.447042,73.316520,3.281500,2.822375,1.187667,0.187667,4.602954,0.370964,Low

In [ ]:
df.columns

Index(['study_hours', 'attendance', 'assignment_completion', 'midterm_score',
       'final_score', 'project_score', 'backlogs', 'sleep_hours', 'stress',
       'anxiety', 'depression', 'motivation', 'concentration',
       'time_management', 'self_discipline', 'social_media_hours',
       'gaming_hours', 'netflix_hours', 'screen_time', 'physical_activity',
       'junk_food_frequency', 'caffeine_mg', 'late_night_frequency',
       'procrastination_score', 'family_income', 'parental_education_level',
       'internet_quality', 'library_visits', 'online_courses_completed',
       'part_time_hours', 'peer_study_group', 'relationship_status',
       'hostel_student', 'extracurricular_hours', 'phone_unlocks_per_day',
       'previous_gpa', 'class_participation', 'weekly_study_sessions',
       'group_study_hours', 'financial_stress', 'gpa', 'performance_level'],
      dtype='object')

In [ ]:
df.dtypes

study_hours                 float64
attendance                  float64
assignment_completion       float64
midterm_score               float64
final_score                 float64
project_score               float64
backlogs                      int64
sleep_hours                 float64
stress                      float64
anxiety                     float64
depression                  float64
motivation                  float64
concentration               float64
time_management             float64
self_discipline             float64
social_media_hours          float64
gaming_hours                float64
netflix_hours               float64
screen_time                 float64
physical_activity           float64
junk_food_frequency         float64
caffeine_mg                 float64
late_night_frequency        float64
procrastination_score       float64
family_income               float64
parental_education_level      int64
internet_quality            float64
library_visits              float64
online_courses_completed      int64
part_time_hours             float64
peer_study_group              int64
relationship_status           int64
hostel_student                int64
extracurricular_hours       float64
phone_unlocks_per_day       float64
previous_gpa                float64
class_participation         float64
weekly_study_sessions       float64
group_study_hours           float64
financial_stress            float64
gpa                         float64
performance_level            object
dtype: object

In [ ]:
df.isna().sum()

In [ ]:
df['performance_level'].value_counts()

performance_level
Low    998442
Name: count, dtype: int64

In [ ]:
df.drop(columns=['performance_level'], inplace=True)

In [ ]:
df.columns

Index(['study_hours', 'attendance', 'assignment_completion', 'midterm_score',
       'final_score', 'project_score', 'backlogs', 'sleep_hours', 'stress',
       'anxiety', 'depression', 'motivation', 'concentration',
       'time_management', 'self_discipline', 'social_media_hours',
       'gaming_hours', 'netflix_hours', 'screen_time', 'physical_activity',
       'junk_food_frequency', 'caffeine_mg', 'late_night_frequency',
       'procrastination_score', 'family_income', 'parental_education_level',
       'internet_quality', 'library_visits', 'online_courses_completed',
       'part_time_hours', 'peer_study_group', 'relationship_status',
       'hostel_student', 'extracurricular_hours', 'phone_unlocks_per_day',
       'previous_gpa', 'class_participation', 'weekly_study_sessions',
       'group_study_hours', 'financial_stress', 'gpa'],
      dtype='object')

## transformation

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler


numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns

minmax_scaler = MinMaxScaler()
df_minmax = df.copy()
df_minmax[numerical_cols] = minmax_scaler.fit_transform(df[numerical_cols])

standard_scaler = StandardScaler()
df_standard = df.copy()
df_standard[numerical_cols] = standard_scaler.fit_transform(df[numerical_cols])


robust_scaler = RobustScaler()
df_robust = df.copy()
df_robust[numerical_cols] = robust_scaler.fit_transform(df[numerical_cols])


print("=== Min-Max Scaling ===")
print(df_minmax.head())

print("\n=== Standard Scaling (Z-score) ===")
print(df_standard.head())

print("\n=== Robust Scaling ===")
print(df_robust.head())

=== Min-Max Scaling ===
   study_hours  attendance  assignment_completion  midterm_score  final_score  \
0     0.251224    0.528657               0.394942       0.572113     0.616535
1     0.305440    0.618351               0.621863       0.575523     0.620628
2     0.225315    0.604646               0.910470       0.445690     0.464828
3     0.287089    0.639384               0.814863       0.520408     0.554489
4     0.016057    0.357860               0.556508       0.328150     0.323780

   project_score  backlogs  sleep_hours    stress   anxiety  ...  \
0       0.653972       0.4     0.347353  0.365330  0.581460  ...
1       0.657155       0.3     0.572542  0.093469  0.419453  ...
2       0.535977       0.2     0.514544  0.318124  0.565558  ...
3       0.605714       0.2     0.466356  0.452578  0.651714  ...
4       0.426273       0.5     0.479021  0.000000  0.307258  ...

   relationship_status  hostel_student  extracurricular_hours  \
0                  1.0             0.0               0.260099
1                  0.0             0.0               0.417771
2                  0.0             1.0               0.737070
3                  0.0             1.0               0.603228
4                  1.0             1.0               0.590459

   phone_unlocks_per_day  previous_gpa  class_participation  \
0               0.439760      0.572113             0.287457
1               0.265457      0.575523             0.424454
2               0.252727      0.445690             0.499308
3               0.261600      0.520408             0.497999
4               0.436924      0.328150             0.202486

   weekly_study_sessions  group_study_hours  financial_stress       gpa
0               0.349027           0.224998          0.499098  0.272132
1               0.351846           0.227818          0.208542  0.351973
2               0.244493           0.120464          0.522672  0.432158
3               0.306274           0.182246          0.621851  0.362964
4               0.147304           0.023276          0.400328  0.184646

[5 rows x 41 columns]

=== Standard Scaling (Z-score) ===
   study_hours  attendance  assignment_completion  midterm_score  final_score  \
0    -0.464290   -0.610445              -1.246447      -0.187077    -0.181898
1    -0.170268   -0.123465              -0.010058      -0.164291    -0.158654
2    -0.604795   -0.197875               1.562438      -1.031741    -1.043563
3    -0.269785   -0.009268               1.041514      -0.532530    -0.534304
4    -1.739632   -1.537763              -0.366149      -1.817053    -1.844680

   project_score  backlogs  sleep_hours    stress   anxiety  ...  \
0      -0.185596  0.877780    -1.160698  0.612518  0.543998  ...
1      -0.162659  0.272084     1.032556 -0.780115 -0.536065  ...
2      -1.035886 -0.333612     0.467675  0.370700  0.437980  ...
3      -0.533350 -0.333612    -0.001650  1.059460  1.012367  ...
4      -1.826428  1.483477     0.121703 -1.258922 -1.284040  ...

   relationship_status  hostel_student  extracurricular_hours  \
0             1.494610       -0.999716              -1.042511
1            -0.669071       -0.999716               0.146763
2            -0.669071        1.000284               2.555138
3            -0.669071        1.000284               1.545609
4             1.494610        1.000284               1.449293

   phone_unlocks_per_day  previous_gpa  class_participation  \
0               0.686912     -0.187077            -0.829536
1              -0.583397     -0.164291            -0.110003
2              -0.676173     -1.031741             0.283141
3              -0.611502     -0.532530             0.276263
4               0.666244     -1.817053            -1.275816

   weekly_study_sessions  group_study_hours  financial_stress       gpa
0              -0.188210          -0.492480          0.368117 -0.963347
1              -0.165479          -0.476418         -1.582879 -0.420138
2              -1.030852          -1.087902          0.526412  0.125417
3              -0.532836          -0.735997          1.192371 -0.345353
4              -1.814284          -1.641484         -0.295090 -1.558575

[5 rows x 41 columns]

=== Robust Scaling ===
   study_hours  attendance  assignment_completion  midterm_score  final_score  \
0    -0.319799   -0.448638              -0.910914      -0.138958    -0.138958
1    -0.109619   -0.097474              -0.013456      -0.122131    -0.122131
2    -0.420239   -0.151132               1.127972      -0.762742    -0.762742
3    -0.180758   -0.015127               0.749849      -0.394075    -0.394075
4    -1.231472   -1.117332              -0.271932      -1.342694    -1.342694

   project_score  backlogs  sleep_hours    stress   anxiety  ...  \
0      -0.138958  0.666667    -0.860162  0.455677  0.403804  ...
1      -0.122131  0.333333     0.767383 -0.442583 -0.396715  ...
2      -0.762742  0.000000     0.348202  0.299703  0.325225  ...
3      -0.394075  0.000000    -0.000069  0.743959  0.750948  ...
4      -1.342694  1.000000     0.091467 -0.751417 -0.951097  ...

   relationship_status  hostel_student  extracurricular_hours  \
0                  1.0             0.0              -0.769679
1                  0.0             0.0               0.109115
2                  0.0             1.0               1.888743
3                  0.0             1.0               1.142769
4                  1.0             1.0               1.071597

   phone_unlocks_per_day  previous_gpa  class_participation  \
0               0.508352     -0.138958            -0.605918
1              -0.428330     -0.122131            -0.078605
2              -0.496739     -0.762742             0.209513
3              -0.449054     -0.394075             0.204472
4               0.493113     -1.342694            -0.932977

   weekly_study_sessions  group_study_hours  financial_stress       gpa
0              -0.138958          -0.505181          0.273426 -0.696097
1              -0.122132          -0.495511         -1.169236 -0.302563
2              -0.762742          -0.863654          0.390477  0.092669
3              -0.394075          -0.651790          0.882919 -0.248385
4              -1.342694          -1.196938         -0.216982 -1.127316

[5 rows x 41 columns]